on:
  push:
    tags:
    - 'v*'

name: Release

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Check npm version
      run: npm -v
    - name: Install dependencies
      run: npm ci
    - name: Build library
      run: npm run build
    - name: Run tests
      run: npm test
  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Check npm version
      run: npm -v
    - name: Install project dependencies
      run: npm ci
    - name: Build library
      run: npm run build
    - name: Get latest release version number
      id: get_version
      uses: battila7/get-version-action@v2
    - name: Show latest release version number
      run: echo ${{ steps.get_version.outputs.version-without-v }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Publish
      if: success()
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
